# Generated by Django 4.1.2 on 2022-10-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('number_of_players', models.IntegerField()),
                ('average_age', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('world_cup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('dob', models.DateField()),
                ('height', models.IntegerField()),
                ('value', models.IntegerField()),
                ('leg', models.IntegerField(choices=[(1, 'left-footed'), (2, 'right-footed'), (3, 'both')])),
                ('sponsor', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_participants', models.IntegerField()),
                ('club', models.ManyToManyField(to='FootballCenter_app.club')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('value_of_transfer', models.IntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FootballCenter_app.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FootballCenter_app.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ManyToManyField(through='FootballCenter_app.PlayerInClub', to='FootballCenter_app.club'),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FootballCenter_app.nationality'),
        ),
    ]
